import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
require("dotenv").config();

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "AI Email Chain",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
        style={{
          minHeight: "100vh",
          background: "linear-gradient(135deg, #232526 0%, #414345 100%)",
        }}
      >
        <div className="flex-1 flex flex-col min-h-screen">
          <main className="flex-1 w-full max-w-6xl mx-auto px-4 py-8 flex flex-col gap-8">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
